openapi: 3.0.3
info:
  title: ICS Island Management Service API
  description: ICS native service for managing compute islands
  version: 1.0.0
  contact:
    name: ICS API Support
    email: api@islandcomputing.io

servers:
  - url: https://IMS.ap-in-1.IslandComputing.io
    description: ICS Asia Pacific (India) Region 1

paths:
  /:
    post:
      summary: Execute Island Management Actions
      description: Perform various island management operations
      requestBody:
        required: true
        content:
          application/x-ics-json-1.0:
            schema:
              oneOf:
                - $ref: '#/components/schemas/LaunchIslandRequest'
                - $ref: '#/components/schemas/DescribeIslandsRequest'
                - $ref: '#/components/schemas/ModifyIslandRequest'
                - $ref: '#/components/schemas/TerminateIslandsRequest'
                - $ref: '#/components/schemas/ScaleIslandRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/x-ics-json-1.0:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/LaunchIslandResponse'
                  - $ref: '#/components/schemas/DescribeIslandsResponse'
                  - $ref: '#/components/schemas/ModifyIslandResponse'
                  - $ref: '#/components/schemas/TerminateIslandsResponse'
                  - $ref: '#/components/schemas/ScaleIslandResponse'
        '400':
          description: Bad Request
          content:
            application/x-ics-json-1.0:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Resource Not Found
          content:
            application/x-ics-json-1.0:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    # Request Models
    LaunchIslandRequest:
      type: object
      required:
        - Action
        - Name
        - OrganizationId
        - InstanceType
        - EnvironmentType
      properties:
        Action:
          type: string
          enum: [LaunchIsland]
        Name:
          type: string
          minLength: 1
          maxLength: 255
        OrganizationId:
          type: string
          pattern: '^org-[a-zA-Z0-9-]+$'
        InstanceType:
          type: string
          enum: [t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge]
        EnvironmentType:
          type: string
          enum: [development, testing, staging, production, sandbox]
        Description:
          type: string
          maxLength: 1000
        MinSize:
          type: integer
          minimum: 0
          maximum: 1000
          default: 1
        MaxSize:
          type: integer
          minimum: 0
          maximum: 1000
          default: 10
        VolumeSize:
          type: integer
          minimum: 1
          maximum: 16384
          default: 20
        VolumeType:
          type: string
          enum: [gp3, gp2, io1, io2]
          default: "gp3"

    # Response Models
    LaunchIslandResponse:
      type: object
      required:
        - Island
        - ResponseMetadata
      properties:
        Island:
          $ref: '#/components/schemas/Island'
        ResponseMetadata:
          $ref: '#/components/schemas/ResponseMetadata'

    # Core Island Model
    Island:
      type: object
      required:
        - IslandId
        - Name
        - State
        - InstanceType
        - EnvironmentType
        - LaunchTime
      properties:
        IslandId:
          type: string
          pattern: '^irn:ics:core:ap-in-1:organization/[a-zA-Z0-9-]+:island/[a-zA-Z0-9-]+$'
          example: "irn:ics:core:ap-in-1:organization/org-123456:island/isl-abcdef123"
        Name:
          type: string
          minLength: 1
          maxLength: 255
          example: "web-production-island"
        Description:
          type: string
          maxLength: 1000
          example: "Production web application island"
        State:
          type: string
          enum: [pending, running, stopping, stopped, shutting-down, terminated]
          example: "running"
        InstanceType:
          type: string
          enum: [t3.micro, t3.small, t3.medium, t3.large, t3.xlarge, t3.2xlarge]
          example: "t3.small"
        EnvironmentType:
          type: string
          enum: [development, testing, staging, production, sandbox]
          example: "production"
        LaunchTime:
          type: string
          format: date-time
          example: "2025-09-07T22:00:00.000Z"

    ResponseMetadata:
      type: object
      required:
        - RequestId
      properties:
        RequestId:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

    ErrorResponse:
      type: object
      required:
        - Error
        - RequestId
      properties:
        Error:
          type: object
          required:
            - Code
            - Message
          properties:
            Code:
              type: string
              example: "InvalidIslandId.NotFound"
            Message:
              type: string
              example: "The island ID does not exist"
        RequestId:
          type: string
          pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
